import test from 'node:test';
import assert from 'node:assert/strict';
import {api,request,routePath,ApiError} from '../src/api.js';
test('path parameters are mandatory and encoded',()=>{assert.equal(routePath('/{id}',{id:'a/b'}),'/a%2Fb');assert.throws(()=>routePath('/{id}',{}),/Missing/);});
test('negotiation acceptance preserves PUT route and session credentials',async()=>{const old=globalThis.fetch;let call;globalThis.fetch=async(...args)=>{call=args;return new Response(JSON.stringify({message:'Accepted'}));};try{await api('acceptProposal',{negotiationId:18});assert.equal(call[0],'/api/v1/request-negotiation/18/accept');assert.equal(call[1].method,'PUT');assert.equal(call[1].credentials,'include');assert.equal(call[1].headers['X-Requested-With'],'XMLHttpRequest');}finally{globalThis.fetch=old;}});
test('registration sends backend DTO fields as JSON',async()=>{const old=globalThis.fetch;let call;globalThis.fetch=async(...args)=>{call=args;return new Response('{}');};const dto={email:'test@example.com',password:'test-only-password',name:'Test',phone:'0500000000'};try{await api('registerIndividual',{}, {body:dto});assert.equal(call[0],'/api/v1/account/register/individual');assert.equal(call[1].method,'POST');assert.deepEqual(JSON.parse(call[1].body),dto);}finally{globalThis.fetch=old;}});
test('CV uses file multipart field without overriding boundary',async()=>{const old=globalThis.fetch;let call;globalThis.fetch=async(...args)=>{call=args;return new Response('{}');};try{const form=new FormData();form.append('file',new Blob(['test-only-pdf']), 'cv.pdf');await api('extractCv',{}, {body:form});assert.equal(call[0],'/api/v1/ai/cv/extract-skills');assert.equal(call[1].body,form);assert.equal(call[1].headers['Content-Type'],undefined);}finally{globalThis.fetch=old;}});
test('backend validation messages remain intact',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({message:'Please verify your email first'}),{status:400});try{await assert.rejects(()=>api('createRequest',{offerId:1},{body:{mode:'ONLINE'}}),error=>error instanceof ApiError && error.status===400 && error.message==='Please verify your email first');}finally{globalThis.fetch=old;}});
test('network failure never becomes a successful action',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>{throw new TypeError('offline');};try{await assert.rejects(()=>api('bonus'),e=>e.status===0);}finally{globalThis.fetch=old;}});
