import React, { useCallback, useEffect, useState } from 'react';
import { Routes, Route, Link, NavLink, Navigate, useNavigate } from 'react-router-dom';
import { ArrowUpRight, ArrowLeftRight, BookOpen, Layers, LayoutDashboard, Wallet as WalletIcon, Sparkles, User, Shield, Menu, X, CalendarDays, MessageCircle, Plus, Globe, LogOut } from 'lucide-react';
import { api } from './api';
import { translate } from './i18n';
import { AppContext, useApp, useResource, Resource, Button, Header, Badge, Empty, Form, ModalHost, Stat, Action, profileFields, f } from './ui';
import { Discover, Skills, Offers, Provider } from './Marketplace';
import { Requests, RequestDetail, Exchanges, ExchangeDetail, Sessions } from './ExchangePages';
import { Wallet, AIStudio, Profile, Assessment, Admin } from './AccountPages';

function Layout({children}) {
 const {user, lang, setLang, t, logout} = useApp(); const [mobile,setMobile] = useState(false);
 const nav = [['/discover','Discover',BookOpen],['/dashboard','Dashboard',LayoutDashboard],['/skills','My skills',Layers],['/offers','My offers',Plus],['/requests','Requests',MessageCircle],['/exchanges','Exchanges',ArrowLeftRight],['/sessions','Sessions',CalendarDays],['/wallet','Wallet',WalletIcon],['/ai','AI studio',Sparkles],['/profile','Profile',User]];
 return <div className={user ? 'app-shell':'public-shell'}><header className="topbar"><Link to="/" className="brand">NAWALL<span>ناول</span><i>↔</i></Link><div className="top-actions"><button className="language" onClick={()=>setLang(lang==='en'?'ar':'en')}><Globe size={16}/>{lang==='en'?'العربية':'English'}</button>{!user ? <><Link className="login-link" to="/login">{t('Log in')}</Link><Link className="btn primary small" to="/register">{t('Join Nawall')}<ArrowUpRight size={16}/></Link></> : <><Link to="/wallet" className="wallet-pill">◈ {user.tokenBalance ?? '—'} <span>{t('tokens')}</span></Link><Link className="avatar" to="/profile" aria-label={t('Profile')}>{user.name?.slice(0,1) || 'N'}</Link><button className="icon-btn mobile-menu" aria-label={t('Menu','القائمة')} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></>}</div></header>{user && <aside className={`sidebar ${mobile?'is-open':''}`}><div className="sidebar-caption">{t('Your exchange space','مساحتك للتبادل')}</div><nav>{nav.map(([path,label,Icon])=><NavLink key={path} to={path} onClick={()=>setMobile(false)}><Icon size={19}/>{t(label)}</NavLink>)}{user.accountType==='ADMIN' && <NavLink to="/admin"><Shield size={19}/>{t('Admin')}</NavLink>}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span>↔</span><p>{t('A little give. A lot to gain.')}</p></div><button onClick={logout}><LogOut size={17}/>{t('Log out')}</button></div></aside>}<main>{children}</main>{!user && <footer><Link to="/" className="brand">NAWALL<span>ناول</span></Link><p>{t('Made for curious people.')}</p><Link to="/discover">{t('Explore skills')} ↗</Link></footer>}</div>;
}
function Landing() {
 const {t} = useApp();
 return <><section className="hero"><div className="hero-copy"><div className="eyebrow">{t('SKILL EXCHANGE, REIMAGINED','تبادل المهارات برؤية جديدة')}</div><h1>{t('Teach what you know.')}<em>{t('Learn what you need.')}</em></h1><p>{t('Your knowledge is someone else’s next chapter.')}<br/>{t('Exchange skills, earn tokens, and grow together.')}</p><div className="actions"><Link className="btn primary" to="/register">{t('Get started')}<ArrowUpRight size={18}/></Link><Link className="text-link" to="/discover">{t('Explore skills')} →</Link></div><div className="hero-foot"><span className="token-stamp">3</span><span>{t('Your first 3 tokens are on us.')}</span></div></div><div className="hero-art"><img src="/reference-Im0.jpg" alt={t('Collage of people exchanging knowledge in a colorful city','عمل فني لأشخاص يتبادلون المعرفة في مدينة ملونة')}/><div className="art-label">{t('Knowledge becomes currency.')}<ArrowLeftRight size={24}/></div></div></section><div className="ticker"><span>{t('LEARN SOMETHING NEW','تعلّم شيئًا جديدًا')}</span><span>✳</span><span>{t('SHARE WHAT YOU KNOW','شارك ما تعرفه')}</span><span>✳</span><span>{t('GROW TOGETHER','انموا معًا')}</span><span>✳</span><span>{t('MAKE KNOWLEDGE COUNT','اجعل المعرفة ذات قيمة')}</span></div><section className="landing-section"><div className="page-heading"><div><div className="eyebrow">{t('How it works')}</div><h2>{t('A little give. A lot to gain.')}</h2></div><p>{t('A community of individuals and companies exchanging what they know.')}</p></div><div className="steps">{[['01','Sign up & add your skills','Build your profile and start with 3 tokens.'],['02','Verify what you know','Take an AI assessment to unlock teaching.'],['03','Teach, learn, repeat','Earn by sharing. Spend on your next skill.']].map(([n,title,desc])=><article key={n}><span>{n}</span><h3>{t(title)}</h3><p>{t(desc)}</p></article>)}</div></section><section className="landing-cta"><Sparkles/><h2>{t('Make room for something new.')}</h2><Link className="btn cream" to="/discover">{t('Find your next teacher')}<ArrowUpRight size={18}/></Link></section></>;
}
function Auth({register = false}) {
 const {t,setUser} = useApp(); const navigate = useNavigate(); const [type,setType]=useState('INDIVIDUAL');
 const fields = [f('email',{required:true,type:'email',maxLength:150}),f('password',{required:true,type:'password',minLength:8,maxLength:255}),...(register?profileFields(type==='COMPANY'):[])];
 return <div className="auth-layout"><div className="auth-story"><span className="eyebrow">NAWALL · ناول</span><h1>{t('Knowledge becomes currency.')}</h1><div className="auth-art"><img src="/reference-Im0.jpg" alt=""/></div><p>{t('Teach what you know.')}<br/>{t('Learn what you need.')}</p></div><div className="auth-card"><div className="eyebrow">{t(register?'Your first 3 tokens are on us.':'Welcome back')}</div><h1>{t(register?'Create account':'Log in')}</h1>{register && <div className="tabs">{['INDIVIDUAL','COMPANY'].map(v=><button key={v} className={type===v?'selected':''} onClick={()=>setType(v)}>{t(v)}</button>)}</div>}<Form key={type} fields={fields} label={register?'Create account':'Log in'} submit={async body=> {if(register) {const registered=await api(type==='COMPANY'?'registerCompany':'registerIndividual',{}, {body});navigate('/login?registered=1');return registered;} await api('login',{}, {body:{email:body.email,password:body.password}}); const profile=await api('profile');setUser(profile);navigate('/dashboard');return {message:t('Welcome back')};}}/><p className="auth-switch">{t(register?'Already a member?':'New to Nawall?')} <Link to={register?'/login':'/register'}>{t(register?'Log in':'Join Nawall')}</Link></p></div></div>;
}
function Dashboard() {
 const {user,t} = useApp(); const state=useResource(signal=>api('dashboard',{}, {signal}));
 return <div className="page"><Header eyebrow={t('Dashboard')} title={t('Your learning, at a glance.')} subtitle={`${t('Welcome back')}, ${user.name}.`}><Link className="btn primary" to="/discover">{t('Explore skills')}<ArrowUpRight size={17}/></Link></Header><Resource state={state}>{d=><><div className="stats"><Stat label={t('Available tokens')} value={d.tokenBalance} note={t('Your next skill starts here.','مهارتك القادمة تبدأ هنا.')}/><Stat label={t('Reserved tokens')} value={d.reservedTokens}/><Stat label={t('Published offers')} value={d.publishedOffers}/><Stat label={t('Total exchanges')} value={d.totalExchanges}/></div><div className="dashboard-split"><article className="panel dark-panel"><div className="eyebrow">{t('Knowledge becomes currency.')}</div><h2>{t('A little give. A lot to gain.')}</h2><p>{t('Earn by sharing. Spend on your next skill.')}</p><Link className="btn cream" to="/skills">{t('My skills')}<ArrowUpRight size={17}/></Link><span className="giant-arrow">↔</span></article><article className="panel"><h3>{t('Exchanges')}</h3><div className="status-grid">{Object.entries(d.exchangesByStatus || {}).map(([k,v])=><Link to={`/exchanges?status=${k}`} key={k}><Badge>{k}</Badge><strong>{v}</strong></Link>)}</div></article></div><div className="stats compact"><Stat label={t('Requests sent')} value={d.requestsSent}/><Stat label={t('Requests received')} value={d.requestsReceived}/><Stat label={t('Teaching earnings')} value={d.tokensEarnedFromTeaching}/><Stat label={t('Average rating')} value={d.averageRating ?? '—'}/></div></>}</Resource></div>;
}
function Protected({children,admin}) { const {user,authLoading,t,authError,refreshUser} = useApp(); if(authLoading) return <div className="loading">{t('Loading…')}</div>; if(authError) return <div className="page error-panel"><p>{authError}</p><Button onClick={refreshUser}>{t('Try again')}</Button></div>; if(!user) return <Navigate to="/login" replace/>; if(admin && user.accountType !== 'ADMIN') return <Navigate to="/dashboard" replace/>; return children; }
function Verification() { const {t,refreshUser} = useApp(); const query = new URLSearchParams(location.search); return <div className="page narrow"><Header title={t('Verify email')}/><Form fields={[f('accountId',{label:'Account ID',type:'number',required:true,min:1}),f('token',{label:'Verification token',required:true,maxLength:64})]} initial={{accountId:query.get('accountId') || '',token:query.get('token') || ''}} label="Verify" submit={values=>api('verifyEmail',{}, {query:values})} after={refreshUser}/></div>; }
export default function App() {
 const [lang,setLang] = useState(()=>localStorage.getItem('nawall-language') || 'en'); const t=translate(lang);
 const [user,setUser]=useState(null),[authLoading,setAuthLoading]=useState(true),[authError,setAuthError]=useState(''),[modal,setModal]=useState(null),[notice,setNotice]=useState(null);
 const refreshUser = useCallback(async()=>{setAuthError('');try {const u=await api('profile');setUser(u);return u;}catch(e){if(e.status===401){setUser(null);}else {setAuthError(e.message);} }finally{setAuthLoading(false);}},[]);
 useEffect(()=> {refreshUser(); const clear=()=>setUser(null);window.addEventListener('nawall:unauthorized',clear);return()=>window.removeEventListener('nawall:unauthorized',clear);},[refreshUser]);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('nawall-language',lang);},[lang]);
 useEffect(()=>{if(notice){const id=setTimeout(()=>setNotice(null),6000);return()=>clearTimeout(id);}},[notice]);
 const toast=(message,type='success')=>setNotice({message,type}); const dialog=config=>setModal(config ? {...config,key:Date.now()} : null);
 const logout=async()=> {try{await api('logout');setUser(null);window.location.assign('/');}catch(e){toast(e.message,'error');}};
 const ctx={lang,setLang,t,user,setUser,authLoading,authError,refreshUser,toast,dialog,logout};
 return <AppContext.Provider value={ctx}><Layout>{user && !user.emailVerified && user.accountType!=='ADMIN' && <div className="verification-banner"><span>{t('Verify your email to start exchanging.')}</span><Action action="sendVerification">{t('Send verification email')}</Action><Button variant="text" onClick={refreshUser}>{t('Check verification')}</Button></div>}<Routes><Route path="/" element={user?<Navigate to="/dashboard" replace/>:<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/verify-email" element={<Verification/>}/><Route path="/discover" element={<Discover/>}/><Route path="/providers/:id" element={<Provider/>}/>{[['/dashboard',<Dashboard/>],['/skills',<Skills/>],['/offers',<Offers/>],['/requests',<Requests/>],['/requests/:id',<RequestDetail/>],['/exchanges',<Exchanges/>],['/exchanges/:id',<ExchangeDetail/>],['/sessions',<Sessions/>],['/wallet',<Wallet/>],['/ai',<AIStudio/>],['/profile',<Profile/>],['/assessments/:id',<Assessment/>]].map(([path,page])=><Route key={path} path={path} element={<Protected>{page}</Protected>}/>)}<Route path="/admin" element={<Protected admin><Admin/></Protected>}/><Route path="*" element={<div className="page"><Empty title={t('Page not found','الصفحة غير موجودة')}><Link className="btn primary" to="/discover">{t('Back to discover')}</Link></Empty></div>}/></Routes></Layout><ModalHost modal={modal} close={()=>setModal(null)}/>{notice && <div className={`toast ${notice.type}`} role={notice.type==='error'?'alert':'status'}>{notice.message}<button aria-label={t('Close')} onClick={()=>setNotice(null)}><X size={17}/></button></div>}</AppContext.Provider>;
}
