import React, {useState} from 'react';
import {Link, useParams} from 'react-router-dom';
import {ArrowUpRight, Search, Plus, ShieldCheck, Users, Monitor, MapPin, ArrowLeftRight,Coins,Asterisk,Star,ArrowRight} from 'lucide-react';
import {api} from './api';
import OfferComposer from './OfferComposer';
import {can} from './rules';
import {useApp,useResource,Resource,Header,Button,Badge,Empty,Action,Result,Field,f,modes,offerFields,DateText,RatingStars} from './ui';

export function OfferCard({offer, mine=false, reload}) {
 const {user,t,dialog,refreshUser} = useApp();
 const learn = ()=>dialog({title:t('Request to learn'),text:`${offer.skillName} · ${offer.tokenCost} ${t('tokens')}`,fields:[f('mode',{options:offer.mode==='BOTH'?modes:[offer.mode],required:true}),f('description',{type:'textarea',maxLength:500,wide:true})],initial:{mode:offer.mode==='BOTH'?'ONLINE':offer.mode},label:'Send',submit:body=>api('createRequest',{offerId:offer.id},{body}),after:refreshUser});
 const details = ()=>dialog({title:offer.skillName,content:<><Result data={{description:offer.description,mode:offer.mode,tokenCost:offer.tokenCost,capacity:offer.capacity,status:offer.status}}/><Link className="btn secondary" to={`/providers/${offer.providerAccountId}`} onClick={()=>dialog(null)}>{t('View provider')}</Link></>});
 return <article className="offer-card"><div className="offer-top"><span className="skill-glyph">{offer.skillName?.slice(0,2).toUpperCase() || <ArrowLeftRight aria-hidden="true"/>}</span><Badge>{offer.status}</Badge></div><div className="offer-provider"><ShieldCheck size={14}/><Link to={`/providers/${offer.providerAccountId}`}>{t('Provider')} #{offer.providerAccountId}</Link></div><h3>{offer.skillName}</h3><p>{offer.description || t('Real skills. Meaningful connections.')}</p><div className="offer-meta"><span>{offer.mode==='ONLINE'?<Monitor size={15}/>:offer.mode==='IN_PERSON'?<MapPin size={15}/>:<ArrowLeftRight size={15}/>} {t(offer.mode)}</span><span><Users size={15}/>{offer.capacity}</span></div><div className="offer-bottom"><strong><span><Coins size={18} aria-hidden="true"/></span> {offer.tokenCost}<small>{t('tokens')}</small></strong>{mine ? <Button variant="secondary" onClick={()=>dialog({title:t('Edit'),fields:offerFields,initial:offer,submit:body=>api('updateOffer',{id:offer.id},{body}),after:reload})} disabled={offer.status==='CANCELLED'}>{t('Edit')}</Button> : <Button variant="text" onClick={details}>{t('Details')}<ArrowUpRight size={18}/></Button>}</div>{mine ? <div className="actions"><Link className="btn text" to={`/sessions?offer=${offer.id}`}>{t('Sessions')}</Link><Action action="deleteOffer" params={{id:offer.id}} confirm={t('Delete this offer? Offers with exchanges cannot be deleted.','حذف العرض؟ لا يمكن حذف عرض مرتبط بتبادلات.')} done={reload} variant="text">{t('Delete')}</Action></div> : user ? <><Button variant="primary" onClick={learn} disabled={!can.requestOffer(user,offer)}>{t('Request to learn')}</Button>{!can.requestOffer(user,offer) && <small className="muted">{user.accountId===offer.providerAccountId?t('Your offer','عرضك'):!user.emailVerified?t('Verify your email to start exchanging.'):t('You need enough tokens for this offer.','تحتاج رموزًا كافية لهذا العرض.')}</small>}</> : <Link className="btn primary" to="/login">{t('Log in')}</Link>}</article>;
}
export function Discover() {
 const {t,user,dialog} = useApp();const [search,setSearch]=useState(''),[mode,setMode]=useState(''),[skill,setSkill]=useState('');
 const offers=useResource(signal=>api(skill?'skillOffers':'offers',skill?{skillId:skill}:{},{signal}),[skill]); const catalog=useResource(signal=>api('skills',{}, {signal}));
 const items = (offers.data || []).filter(o=>o.status==='ACTIVE' && (!mode || o.mode===mode || o.mode==='BOTH') && `${o.skillName} ${o.description || ''}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="page discover"><Header eyebrow={t('THE KNOWLEDGE MARKET','سوق المعرفة')} title={t('Find your next teacher')} subtitle={t('Real skills. Meaningful connections.')}>{user && <Link className="btn secondary" to="/offers"><Plus size={17}/>{t('Create offer')}</Link>}</Header><div className="discover-banner"><div><span className="eyebrow">{t('Made for curious people.')}</span><h2>{t('Learn what you need.')}</h2><p>{t('Earn by sharing. Spend on your next skill.')}</p></div><span className="banner-art"><ArrowLeftRight aria-hidden="true"/><i><Asterisk aria-hidden="true"/></i></span></div><div className="filter-bar"><label className="search-input"><Search size={19}/><input aria-label={t('Search skills or descriptions')} placeholder={t('Search skills or descriptions')} value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label={t('Skills')} value={skill} onChange={e=>setSkill(e.target.value)}><option value="">{t('All skills')}</option>{catalog.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label={t('Mode')} value={mode} onChange={e=>setMode(e.target.value)}><option value="">{t('All modes')}</option>{modes.map(m=><option key={m} value={m}>{t(m)}</option>)}</select></div>{catalog.error && <p className="form-error">{catalog.error.message}</p>}<div className="section-label"><h3>{t('Available offers','العروض المتاحة')}</h3><span>{offers.loading?'…':items.length} {t('offers','عرض')}</span></div><Resource state={offers}>{()=>items.length?<div className="offer-grid">{items.map(o=><OfferCard key={o.id} offer={o}/>)}</div>:<Empty title={t('No offers found','لا توجد عروض')} text={t('Try another search or check back when teachers publish new offers.','جرّب بحثًا آخر أو عد عندما ينشر المعلّمون عروضًا جديدة.')}/>}</Resource>{user && <div className="panel search-tools"><h3>{t('Search providers')}</h3><p>{t('Find verified teachers and open requests for a catalog skill.','ابحث عن معلّمين موثّقين وطلبات مفتوحة لمهارة.')}</p><div className="actions"><Button disabled={!skill} variant="secondary" onClick={()=>dialog({title:t('Search providers'),content:<Lookup action="providers" params={{skillId:skill}} providers/>})}>{t('Search providers')}</Button><Button disabled={!skill} variant="secondary" onClick={()=>dialog({title:t('Search requests'),content:<Lookup action="searchRequests" params={{skillId:skill}}/>})}>{t('Search requests')}</Button></div></div>}</div>;
}
export function Lookup({action,params,providers=false}) { const state=useResource(signal=>api(action,params,{signal}),[action,JSON.stringify(params)]);return <Resource state={state}>{data=>providers?<div className="result-list">{data.map(p=><div key={p.accountId}><Link to={`/providers/${p.accountId}`}>{p.providerName} <ArrowUpRight className="inline-symbol" aria-hidden="true"/></Link><Result data={{skillName:p.skillName,level:p.level,activeOffers:p.activeOffers}}/></div>)}</div>:<Result data={data}/>}</Resource>; }
export function Skills() {
 const {user,t,dialog}=useApp();const catalog=useResource(signal=>api('skills',{}, {signal}));const mine=useResource(signal=>api('mySkills',{accountId:user.accountId},{signal}));const [selected,setSelected]=useState('');
 return <div className="page"><Header eyebrow={t('My skills')} title={t('Share your superpower.','شارك موهبتك.')} subtitle={t('Verified skills can become teaching offers.')}/><div className="panel skill-add"><div><h3>{t('Add skill')}</h3><p>{t('Pass an assessment with at least 70 to verify a skill.')}</p></div><div className="actions"><select aria-label={t('Skills')} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{t('Select…')}</option>{catalog.data?.map(s=><option key={s.id} value={s.id}>{s.name} · {s.category}</option>)}</select><Action action="addSkill" params={{skillId:selected}} disabled={!selected} done={mine.reload}><Plus size={16}/>{t('Add to my skills')}</Action></div></div>{catalog.error && <p className="form-error">{catalog.error.message}</p>}<Resource state={mine}>{skills=><div className="skill-grid">{skills.map(s=><article className="panel skill-card" key={s.id}><div className="offer-top"><span className="skill-glyph">{s.skillName.slice(0,2)}</span>{s.verified && <ShieldCheck className="verified-icon"/>}</div><span className="eyebrow">{s.category}</span><h3>{s.skillName}</h3><Badge>{s.level}</Badge><p>{t(s.verified?'Verified':'Not verified')}</p><div className="actions"><Link className="btn primary" to={`/assessments/${s.id}`}>{t('Assess skill')}<ArrowUpRight size={17}/></Link><Action action="removeSkill" params={{id:s.id}} confirm={t('Remove this skill and its assessment history?','حذف هذه المهارة وسجل اختباراتها؟')} done={mine.reload} variant="text">{t('Delete')}</Action></div></article>)}</div>}</Resource><div className="panel ai-callout"><div><h3>{t('Make room for something new.')}</h3><p>{t('Import your skills from a CV or LinkedIn.','استورد مهاراتك من السيرة أو لينكدإن.')}</p></div><Link to="/ai" className="btn secondary">{t('AI studio')}<ArrowUpRight size={17}/></Link></div></div>;
}
export function Offers() {
 const {user,t,dialog}=useApp();const state=useResource(signal=>api('providerOffers',{providerId:user.accountId},{signal}));const skills=useResource(signal=>Promise.all([api('verifiedSkills',{accountId:user.accountId},{signal}),api('skills',{}, {signal})]));
 const create=()=>{const [verified,catalog]=skills.data || [[],[]];const options=catalog.filter(s=>verified.some(v=>v.skillName===s.name)).map(s=>({value:s.id,label:s.name}));dialog({title:t('Create offer'),content:<OfferComposer options={options} after={state.reload}/>});};
 return <div className="page"><Header eyebrow={t('My offers')} title={t('What will you teach?','ماذا ستعلّم؟')} subtitle={t('Earn by sharing. Spend on your next skill.')}><Button disabled={skills.loading || !skills.data?.[0]?.length} onClick={create}><Plus size={17}/>{t('Create offer')}</Button></Header>{skills.error && <p className="form-error">{skills.error.message}</p>}{!skills.loading && !skills.error && !skills.data?.[0]?.length && <p className="info-banner">{t('Pass an assessment with at least 70 to verify a skill.')} <Link to="/skills">{t('My skills')} <ArrowUpRight className="inline-symbol" aria-hidden="true"/></Link></p>}<Resource state={state}>{offers=><div className="offer-grid">{offers.map(o=><OfferCard key={o.id} offer={o} mine reload={state.reload}/>)}</div>}</Resource></div>;
}
export function Provider() {
 const {id}=useParams();const {t}=useApp(); const state=useResource(signal=>Promise.all([api('providerOffers',{providerId:id},{signal}),api('verifiedSkills',{accountId:id},{signal}),api('reviews',{accountId:id},{signal}),api('rating',{accountId:id},{signal})]),[id]);
 return <div className="page"><Header eyebrow={t('Provider')} title={`${t('Provider')} #${id}`}><Link to="/discover" className="btn secondary">{t('Back to discover')}</Link></Header><Resource state={state}>{([offers,skills,reviews,rating])=><><div className="panel provider-summary"><span className="avatar large">#{id}</span><div><h2>{t('Verified skills','المهارات الموثّقة')}</h2><p>{skills.map(s=>`${s.skillName} · ${t(s.level)}`).join(' / ') || t('Nothing here yet')}</p></div><strong><Star className="inline-symbol" aria-hidden="true"/> {rating.toFixed?.(1) ?? rating}</strong></div><div className="section-label"><h3>{t('My offers')}</h3></div>{offers.length?<div className="offer-grid">{offers.map(o=><OfferCard key={o.id} offer={o}/>)}</div>:<Empty/>}<div className="section-label"><h3>{t('Reviews')}</h3></div>{reviews.length?<div className="review-grid">{reviews.map(r=><article className="panel" key={r.id}><span className="stars"><RatingStars rating={r.rating}/></span><p>{r.comment}</p><small><DateText value={r.createdAt}/></small></article>)}</div>:<Empty title={t('No reviews yet','لا توجد تقييمات بعد')}/>}</>}</Resource></div>;
}
